-- take a copy of the lkAFEDescription table before doing any updates.
select * into lkAFEDesc_09222004 from lkAFEDescription 


-- delete staffing plans not needed 
delete tblStaffingPlandetail where currentmonth = '200410'
delete tblStaffingPlan where currentmonth = '200410'


-- update the lkAFEDescription table, set status code to inactive and set lastupdatedate to current date
update lkAFEDescription
set afestatusid = 1201, lastupdatedate = getdate()
where description in (

	'ACI Real Time Feed'
	,'ACS Lift Data Capture'
	,'ADP Project'
	,'Airport Check In'	
	,'Airport Services Stations And ATOs'
	,'Alternate CG Calculation'
	,'AMEX Real Time Update'
	,'AMOSS Phase II'
	,'APIS MEX & CAN'
	,'Application Tower Lead'
	,'Asset Management Coordination'
	,'ATRE E-Fair Support'
	,'Cargo Trac EDI For ACI'
	,'Chemical Management System'
	,'CMI Payroll Scheduling'
	,'CMI Support'
	,'CO-Rel Reduce FOCUS Reports'
	,'CO Connections'
	,'Co Ticketing Auto Non-Refundable'
	,'CO USPS EDI-INT Platform'
	,'CO/COPA Codeshare'
	,'CO/Delta Codeshare - HOU'	
	,'CO/NW/DL ETKT'
	,'CO/Virgin Codeshare'
	,'COBRA PPBM Support'
	,'Codeshare Partner Expansion'
	,'Codeshare With Emirates'
	,'Codeshare With TAP'
	,'COEX Air Support'
	,'COEX Crew Migration COSMOS Support'
	,'COEX FOMS And ACARS Support'
	,'COEX MRO Support'
	,'Collection Of Security Fees'
	,'Continental Express Migration Development'
	,'Continental Express Migration Support'
	,'Continental Express Support'
	,'Conversion From NPC To Chase'
	,'COPA A/C Times Tracking'
	,'Costa Rica APIS Data Transmission'
	,'COSTAR Enhancement 30-Day Notice'
	,'Costar Enhancements AFE'
	,'COSTAR Y-Seat Support'
	,'CREW APIS Reporting Modification'	
	,'Customer Information System Rel 4-5'
	,'Data Warehouse'
	,'DIS Data Migration'	
	,'Disaster Recovery 2003'
	,'EBID Mod'
	,'EDD Automated Station Sales'
	,'EDD Bag Trigger'
	,'EDG - ACC Dev 2003 HOU'
	,'EDG - EDD Dev 2003 HOU'
	,'EDG - ESV Dev 2003 HOU'
	,'EDG Airframe Infrastructure Dev - HOU'
	,'EDG Airframe Infrastructure Dev - LAX'
	,'EDG ATRE eFares HOU'
	,'EDG ATRE eFares LAX'
	,'Electronic Training Records ETR'
	,'Eticket Development 2004'	
	,'Eticket Expansion And Enhancements'
	,'ETicket Server'
	,'Extend ETKT To 45 Days'
	,'EZR Accounting Phase I Support'
	,'EZR OnePass Toolbar Support'
	,'EZR/AirFrame Support'
	,'F/A Contract Pay Items'
	,'F/A Contract Priority II'	
	,'F2F Overide Upgrade Entry'	
	,'FA Jump Seat Enhancement'
	,'Financial Planning Support'
	,'First To Favorite 2003 - HOU'
	,'First To Favorite 2003 - LAX'
	,'First To Favorite 2003 - MIRIMAR'	
	,'First To Favorite 2004 - HOU'
	,'FSIR Datawarehouse'
	,'Host Bulk ETKT'
	,'Host Stock Control'	
	,'Houston Development 2004'
	,'IETKT With ATA'
	,'Increase Booking Compartments'
	,'Increase Selectee Print On Boarding Pass'
	,'Industry Mandate'
	,'Install Shield Support'
	,'Interline Agency E Ticket'
	,'Interline E Ticket Northwest'
	,'Interline Eticket Expansion'
	,'Interline Eticket Expansion - Supplemental'
	,'Interline eTicket With Emirates'
	,'Interline Eticket With Infini'
	,'Interline ETKT With Aeromexico'
	,'Interline ETKT With ATA'
	,'International ETKT With Infini'
	,'ISEP Bond Funded'
	,'JDA And IMS Inactive Status'
	,'KLM Codeshare'
	,'Los Angeles Development 2004'
	,'Marketing Carrier Info'
	,'Marketing Codeshare'
	,'Meeting Works Hardware Upgrade'
	,'Minimum Connect'
	,'Modify JJJ And IVU For Negative Time'
	,'MRO Spirent'
	,'Multi Interline Partners'
	,'MVT Enhancements'
	,'myCOAIR/myTEAM/CHRIS Phase II'
	,'NSK/MQ Series'
	,'Numeric AVS'
	,'OAISys SOC Support'
	,'OAISys SSM Support'
	,'Orbitz'
	,'Original Fudge TCI'
	,'Other Airline Executive Travel'
	,'Overide Upgrade Entry'
	,'PASSUR To FOMS'
	,'Perf Attend/ESPP/ePASS Canada And LA Pricing '
	,'Pilot FAR Flight Time Limitations'
	,'Pilot Training Records Pyramid Support'
	,'PNR MVS2 Testing'
	,'Positive Bag Match'
	,'QA Audit Tech Operations Support'
	,'RASCAL DBA Support'
	,'Rev-Emp Pass Accounting'
	,'Sabre Solution'
	,'Save Passcode'
	,'Seamless Availability Cost By Distribution Channel'
	,'SFR Enhancement 2004'
	,'Simplified Slot Substitutions'
	,'Sky Team Elite Recognition'
	,'Skyteam - Marketing'
	,'Skyteam - Marketing LAX'
	,'SPS For Intl Outbound'
	,'SSM To ITA'
	,'SSR Star Indicator'
	,'Staff Manager Project'
	,'Standby Priority'
	,'Status Code Change'
	,'Superdome - ETA Conversion'	
	,'Technology Vendor'
)
order by description

-- remove rows from the tblStaffingPlandetail table that have inactive AFE Descriptions

select currentmonth, a.afe_descid, locationid
 from tblStaffingPlandetail a , lkAFEDescription b
where currentmonth = '200409'
and a.afe_descid = b.afe_descid
and b.afestatusid = 1201

select distinct a.afe_descid
from tblStaffingPlandetail a , lkAFEDescription b
where currentmonth = '200409'
and a.afe_descid = b.afe_descid
and b.afestatusid = 1201
